### ISSUE TITLE
Could not find or load main class org.wildfly.swarm.bootstrap.Main

### ISSUE THREAD

**Issue by ssi-hu-peter-bartha** [wildfly-swarm/example-jaxrs-shrinkwrap#1] opened 2015-05-10 20:16 UTC
java -jar wildfly-swarm-example-jaxrs-shrinkwrap-1.0.0.Beta1-SNAPSHOT-swarm.jar
Error: Could not find or load main class org.wildfly.swarm.bootstrap.Main

https://gist.github.com/ssi-hu-peter-bartha/68613f8e759cf282b4ab

**Comment by kenfinnigan** [comment] 2015-05-11 15:20
I wasn't able to reproduce the issue.

Could you provide some additional details about your environment? Such as O/S, Maven version, Java version?

Thanks

**Comment by ssi-hu-peter-bartha** [comment] 2015-05-11 15:22
Thanks for checking...

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\peter.bartha>java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

C:\Users\peter.bartha>mvn -v
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: C:\Work\apache-maven-3.3.3
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: C:\Work\jdk1.8.0_45\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 7", version: "6.1", arch: "amd64", family: "dos"

**Comment by kenfinnigan** [comment] 2015-05-13 11:28
Apologies for not realizing this sooner, but can you try building wildfly-swarm master and switching the example to use 1.0.0.Alpha2-SNAPSHOT?

1.0.0.Alpha1 didn't work with Windows, but it should be fixed in current master.

We should be doing a release this week that includes the Windows fix, but it would be a great help if you could verify that the problem is definitely fixed with the latest code.

Thanks
Ken

**Comment by ssi-hu-peter-bartha** [comment] 2015-05-13 11:46
No problem. 
I followed your instructions. 
This is the current status on my machine:
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ wildfly-swarm-example-jaxrs-shrinkwrap ---
[INFO] Building jar: C:\Work\_idea_projects\java_playground\example-jaxrs-shrinkwrap\target\wildfly-swarm-example-jaxrs-shrinkwrap-1.0.0.Beta1-SNAPSHOT.jar
[INFO]
[INFO] --- wildfly-swarm-plugin:1.0.0.Alpha2-SNAPSHOT:create (default) @ wildfly-swarm-example-jaxrs-shrinkwrap ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.192 s
[INFO] Finished at: 2015-05-13T13:44:56+02:00
[INFO] Final Memory: 52M/398M
[INFO] ------------------------------------------------------------------------

C:\Work\_idea_projects\java_playground\example-jaxrs-shrinkwrap>java -jar target\wildfly-swarm-example-jaxrs-shrinkwrap-1.0.0.Beta1-SNAPSHOT.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/wildfly/swarm/container/Deployment
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.wildfly.swarm.container.Deployment
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

**Comment by kenfinnigan** [comment] 2015-05-13 11:49
That's weird.

I'll take another look

**Comment by kenfinnigan** [comment] 2015-05-13 15:45
Just noticed that in the most recent test you made above, you ran the project jar instead of the "-swarm" version in target.

Could you try running the "-swarm" jar and see if you still get this error?

Might also help to rebuild wildfly-swarm master first as I just made a different fix for Windows

**Comment by ssi-hu-peter-bartha** [comment] 2015-05-13 15:55
Thanks, it works now!

http://localhost:8080/
*Howdy at 2015-05-13T17:49:49.235+02:00*

Just a small issue logged by wildfly. 
Maybe it's worth addressing in the example or in swarm.

*2015-05-13 17:49:49,427 WARN  [org.jboss.resteasy.core.ExceptionHandler] (default task-2) failed to execute: javax.ws.rs.NotFoundException: Could not find resource for full path: http://localhost:8080/favicon.ico*

**Comment by kenfinnigan** [comment] 2015-05-13 15:58
That's great.

We're aware of that. For now we will probably just make a note in the README of the examples and raise an issue to look more closely in the future.

**Closed by kenfinnigan** 2015-05-13 15:58 UTC
